### ISSUE TITLE
关于项目命名

### ISSUE THREAD

**Issue by yi-ge** [niceboybao/front-end-develop-standard#1]
关于项目命名，大多数Github项目都是`abc-bcd`，很少见到`abc_bcd`。就连此项目也是这样。

但是在`命名规范`的第一条`项目命名`，却是要求以`abc_bcd`的方式命名。似乎不太科学。

**Comment by niceboybao** [comment]
我有重新参考了资源，确实是这样，谢谢您的issues。规范给项目组还是一个试用期，后续还会补充！
